In [ ]:
# Full classification example
# https://huggingface.co/ruanchaves/bert-large-portuguese-cased-hatebr

# from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
# import numpy as np
# import torch
# from scipy.special import softmax

# model_name = "ruanchaves/bert-large-portuguese-cased-hatebr"
# s1 = "Quem não deve não teme!!"
# model = AutoModelForSequenceClassification.from_pretrained(model_name)
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# config = AutoConfig.from_pretrained(model_name)
# model_input = tokenizer(*([s1],), padding=True, return_tensors="pt")
# with torch.no_grad():
#     output = model(**model_input)
#     scores = output[0][0].detach().numpy()
#     scores = softmax(scores)
#     ranking = np.argsort(scores)
#     ranking = ranking[::-1]
#     for i in range(scores.shape[0]):
#         l = config.id2label[ranking[i]]
#         s = scores[ranking[i]]
#         print(f"{i+1}) Label: {l} Score: {np.round(float(s), 4)}")


In [11]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
import numpy as np
import torch
from scipy.special import softmax

model_name = "ruanchaves/bert-large-portuguese-cased-hatebr"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
config = AutoConfig.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)

In [41]:
s1 = "Quem não deve não teme!!"

sequences = [
    s1,
    "esquerdista do caralho!",
    "bolsonaro genocida!",
    "vadia burra",
    "viadinho"
]

model_input = tokenizer(*(sequences,), padding=True, return_tensors="pt")
with torch.no_grad():
    outputs = model(**model_input)
    print(outputs)
    for logit in outputs.logits:
        print('\n\n', logit)
        scores = logit.detach().numpy()
        scores = softmax(scores)
        print(scores)
        # ranking = np.argsort(scores)
        # ranking = ranking[::-1]  # inverte o ranking
        for i in range(scores.shape[0]):
            l = config.id2label[i]
            s = scores[i]
            print(f"{i+1}) Label: {l} Score: {np.round(float(s), 4)}")

SequenceClassifierOutput(loss=None, logits=tensor([[ 5.4566, -6.0175],
        [-5.6428,  6.1183],
        [-5.7193,  6.1025],
        [-5.7092,  6.1302],
        [-5.7136,  6.1062]]), hidden_states=None, attentions=None)


 tensor([ 5.4566, -6.0175])
[9.9998963e-01 1.0395761e-05]
1) Label: False Score: 1.0
2) Label: True Score: 0.0


 tensor([-5.6428,  6.1183])
[7.8026478e-06 9.9999225e-01]
1) Label: False Score: 0.0
2) Label: True Score: 1.0


 tensor([-5.7193,  6.1025])
[7.3426663e-06 9.9999261e-01]
1) Label: False Score: 0.0
2) Label: True Score: 1.0


 tensor([-5.7092,  6.1302])
[7.2142425e-06 9.9999273e-01]
1) Label: False Score: 0.0
2) Label: True Score: 1.0


 tensor([-5.7136,  6.1062])
[7.357301e-06 9.999926e-01]
1) Label: False Score: 0.0
2) Label: True Score: 1.0


In [29]:
outputs.logits

tensor([[ 5.4566, -6.0175],
        [-5.6428,  6.1183],
        [-5.7193,  6.1025],
        [-5.7092,  6.1302],
        [-5.7136,  6.1062]])

In [35]:
outputs.__dict__

{'loss': None,
 'logits': tensor([[ 5.4566, -6.0175],
         [-5.6428,  6.1183],
         [-5.7193,  6.1025],
         [-5.7092,  6.1302],
         [-5.7136,  6.1062]]),
 'hidden_states': None,
 'attentions': None}

In [10]:

tokens = tokenizer(*([s1],), padding=True, return_tensors="pt")
print(tokens)

{'input_ids': tensor([[  101, 15807,   346,  1981,   346,   376, 22279,   106,   106,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
